<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="hanbingdeMacBook-Air.local" ignored="0" name="Test" tests="4" failures="2" timestamp="13 八月 2020 03:57:06 GMT" time="0.113" errors="0">
  <testcase name="logDem0" time="0.013" classname="con.course.code.Chapter6.TestMethodDemo">
    <failure type="java.lang.RuntimeException" message="这是我自己的运行时异常！">
      <![CDATA[java.lang.RuntimeException: 这是我自己的运行时异常！
	at con.course.code.Chapter6.TestMethodDemo.logDem0(TestMethodDemo.java:27)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- logDem0 -->
  <testcase name="test1" time="0.008" classname="con.course.code.Chapter6.TestMethodDemo">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;1&amp;gt; but was:&amp;lt;2&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<1> but was:<2>
	at con.course.code.Chapter6.TestMethodDemo.test1(TestMethodDemo.java:11)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.005" classname="con.course.code.Chapter6.TestMethodDemo"/>
  <testcase name="test3" time="0.003" classname="con.course.code.Chapter6.TestMethodDemo"/>
</testsuite> <!-- Test -->
